# Generated by Django 4.2 on 2025-01-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pay',
            field=models.BooleanField(default=False),
        ),
    ]
